services:
  youbookingbundle.category_repository:
    class: You\BookingBundle\Repository\CategoryRepository
    factory_service: doctrine.orm.default_entity_manager
    factory_method: getRepository
    arguments:
      - You\BookingBundle\Entity\Category

  youbookingbundle.category_manager:
    class: You\BookingBundle\Manager\CategoryManager
    arguments:
      repository: "@youbookingbundle.category_repository"