services:
  youbookingbundle.service_repository:
    class: You\BookingBundle\Repository\ServiceRepository
    factory_service: doctrine.orm.default_entity_manager
    factory_method: getRepository
    arguments:
      - You\BookingBundle\Entity\Service

  youbookingbundle.service_manager:
    class: You\BookingBundle\Manager\ServiceManager
    arguments:
      repository: "@youbookingbundle.service_repository"